import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return ( 
    <>
      <div className={styles.container}>
        <Head>
          <title>Runners' Shack</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav className='relative container mx-auto bg-emerald-600 p-6'>
          <div className="flex items-center justify-between">
            <div className="hidden md:flex space-x-6">
              <Link href='/contact' className='hover:text-gray-500'><a className='hover:text-red-500'>Pricing</a></Link>
              <Link href='/contact' className='hover:text-gray-500'>Product</Link>
              <Link href='/contact' className='hover:text-gray-500'>Careers</Link>
              <Link href='/contact' className='hover:text-orange-500'>About Us</Link>
              <Link href='/contact' className='hover:text-gray-500'>Community</Link>
              
            </div>
          </div>
        </nav>
        <img className='bg-red-500' src='images/redRunnerMain.png'/>

      </div>
    </>
  )
}
