import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script';
import Link from 'next/link';
import ProductCard from '../components/ProductCard';

export default function Home() {
  return ( 
    <>
      <div className={styles.container}>
        <Head>
          <title>Runners&apos; Shack</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon1.svg" />
        </Head>
        <nav className='relative p-3'>
          <div className="flex items-center md: w-11/12 justify-between">
            <h1 className='text-white'>Runner&apos;s Shack</h1>
            <div className="hidden md:flex space-x-6">
              <Link href='#'><a className='text-white hover:text-highGold'>Products</a></Link>
              <Link href='#'><a className='text-white hover:text-highGold'>Contact</a></Link>
              <Link href='#'><a className='text-white hover:text-highGold'>About Us</a></Link>
              <Link href='#'><a className='text-white hover:text-highGold'>Careers</a></Link>
            </div>
            <button id="menu-btn" className="block hamburger md:hidden focus:outline-none">
              <span className="hamburger-top"></span>
              <span className="hamburger-middle"></span>
              <span className="hamburger-bottom"></span>
            </button>
          </div>

          <div className="md:hidden">
            <div id="menu" className="z-30 absolute flex-col items-center self-end hidden py-8 mt-10 space-y-6 font-bold bg-white sm:w-auto sm:self-center left-6 right-6 drop-shadow-md rounded-2xl">
            <Link href='#'><a className='hover:text-highGold'>Products</a></Link>
              <Link href='#'><a className='hover:text-highGold'>Contact</a></Link>
              <Link href='#'><a className='hover:text-highGold'>About Us</a></Link>
              <Link href='#'><a className='hover:text-highGold'>Careers</a></Link>
            </div>
          </div>

        </nav>
        <section className="md:grid md:grid-cols-2 p-6 overflow-hidden">
          <article className='w-8/12'>
            <h1 className=' text-2xl text-white text-center'>Putting the world in motion</h1>
            <p className='text-white text-center p-5 lg:my-44 inline-block lg:align-middle'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ea.</p>
          </article>
          <div className='relative bg-mainGold rounded-full '>
            <Image layout='fill' className="rotate-[23deg] object-contain sm:w-screen overflow-hidden" src='images/redRunnerMain.png'/>
          </div>
        </section>
        <h2 className='text-center text-xl font-bold'>Our Shoes</h2>
        <section className='bg-highRed md:bg-white m-6 p-3 rounded-md shadow-lg md:shadow-none md:flex shadow-gray-800' >
          <div className="md:font-bold flex-1 md:bg-[url('/images/Ecology_Outline.svg')] md:bg-no-repeat md:bg-[length:80%] md:p-12 lg:p-24">
            <p>Sustainable, eco-friendly materials</p>
          </div>
          <div className="md:font-bold flex-1 md:bg-[url('/images/Innovation_Outline.svg')] md:bg-no-repeat md:bg-[length:80%] md:p-6 lg:p-24">
            <p>Designed with comfort in mind</p>
            <p>Tested for the real world</p>
          </div>
          <div className="md:font-bold flex-1 md:bg-[url('/images/Running_Flatline.svg')] md:bg-no-repeat md:bg-[length:80%] md:p-12 lg:-24">
            <p>Breathable designs for sustained activity</p>
          </div>
        </section>

        <h2 className='text-center text-xl font-bold'>Latest Products</h2>
        <section className='grid grid-cols-2 md:grid-cols-4 '>
          <ProductCard name={'Mudhoppers'} picture='/images/shoe4.png' price={'129.99'}/>
          <ProductCard name={'Springsteppers'} picture='/images/shoe2.png' price={'149.99'}/>
          <ProductCard name={'Trailblazers'} picture='/images/mudskippers.png' price={'179.99'}/>
          <ProductCard name={'Jackrabbits'} picture='/images/shoe3.png' price={'149.99'}/>
        </section>

        <h2 className='text-center text-xl font-bold'>Reviews</h2>
        <section className='bg-mainRed text-white p-6 m-6 rounded-md grid grid-cols-1 md:grid-cols-3 gap-3'>
          <article className='relative bg-highRed p-3'>
            <h3>Roddy Jackman</h3>
            <p className='mb-6'>These are my go to runners for marathons, durable and breathable</p>
            <div className='absolute bottom-0'>

              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-regular.svg' height={20} width={20} />
            </div>
          </article>
          <article className='relative bg-highRed p-3'>
            <h3>Sid Richie</h3>
            <p className='mb-6'>Perfect for long jogs</p>
            <div className='absolute bottom-0'>

              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-regular.svg' height={20} width={20} />
            </div>
          </article>
          <article className='relative bg-highRed p-3'>
            <h3>Rita Winslet</h3>
            <p className='mb-6'>Great for getting around town during the weekends</p>
            <div className='absolute bottom-0'>

              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
              <Image src='/images/star-solid.svg' height={20} width={20} />
            </div>
          </article>

        </section>

        <h2 className='text-center text-xl font-bold'>Contact Us</h2>
        
        <div className='md:flex md:bg-gray-400'>
          <section className='flex-1 grid grid-rows-3 p-6'>
            <div className='flex place-items-center'>
              <Image src='/images/phone-svgrepo-com.svg' height={40} width={40} />
              <p className='p-6'>555-5555-5555</p>
            </div>
            <div className='flex place-items-center'>
              <Image src='/images/email-svgrepo-com.svg' height={40} width={40} />
              <p className='p-6'>runners@fake.com</p>
            </div>
            <div className='flex place-items-center'>
              <Image src='/images/pin-svgrepo-com.svg' height={40} width={40} />
              <div className='p-6'>
                <p>628 Markel St.</p>
                <p>Calgary, AB</p>
              </div>
            </div>
          </section>
          <form className='flex-1 container md:w-1/2'>
            <div className='m-3'>
              <label htmlFor="name" className='clear-left px-2 font-bold'>Name:</label>
              <input className='float-right float-right border border-black  bg-gray-200' id="name" type='text' />
            </div>
            <div className='m-3'>
              <label htmlFor='email' className='clear-left px-2 font-bold mr-auto'>Email:</label>
              <input className='float-right border border-black bg-gray-200' id='email' type='text'></input>
            </div>
            <div className='m-3'>
              <label className='p-2 font-bold block'>Subject:</label>
              <textarea className='border border-black w-full bg-gray-200'></textarea>
            </div>
            <div className='text-center'>
              <button className='border-2 p-4 mb-6 border-mainGold bg-mainRed font-bold rounded-xl text-xl' type='submit'>Submit</button>
            </div>
          </form>
        </div>

      </div>
      <Script src='./javascript/script.js'></Script>
    </>
  )
}
